/// <reference types="@cloudflare/workers-types" />

// Workers runtime globals not exposed as constructors in @cloudflare/workers-types v5
declare class EmailMessage {
  constructor(from: string, to: string, raw: string | ReadableStream);
}

// Generated by running `wrangler types src/workerConfiguration.d.ts`
// Re-run after modifying wrangler.jsonc bindings
declare namespace Cloudflare {
  interface Env {
    DB: D1Database;
    EMAIL: SendEmail;
    FREE_RATE_LIMITER: RateLimit;
    PREMIUM_RATE_LIMITER: RateLimit;
    PUBLIC_API_URL: string;
    PUBLIC_BETTER_AUTH_URL: string;
    PUBLIC_ORIGIN_ALLOWLIST: string;
    PUBLIC_GOOGLE_CLIENT_ID: string;
    EMAIL_FROM_ADDRESS: string;
    EMAIL_FROM_NAME: string;
    GOOGLE_CLIENT_SECRET: string;
    BETTER_AUTH_SECRET: string;
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
  }
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface Env extends Cloudflare.Env {}
